### ISSUE TITLE
TotpUrlError does not implement std::error::Error

### ISSUE THREAD

**Issue by tmpfs** [constantoine/totp-rs#41]
Which means it can't be used with libraries like `anyhow`.

I would recommend using `thiserror` for your error types, I also noticed that you return `Box<dyn Error>` in `get_qr()` which means it can't be used in multi-threaded environments as it is not `Send`.

This means I need to `unwrap()` where ordinarily I would just use `?`.

Happy to submit a PR if you are interested in fixing the ergonomics for error handling.

**Comment by constantoine** [comment]
Hi!

Since TotpUrlError and Rfc6238Error already implements Display, and have derive Debug, just adding `impl std::error::Error for Rfc6238Error {}` and `impl std::error::Error for TotpUrlError {}` does the trick.

As for the Box<dyn Error>, I will simply return a string using the `to_string()` of the two possible error types

Does PR #42 seem satisfactory?

**Comment by tmpfs** [comment]
Sure, thats fine to do it like that 👍
