### ISSUE TITLE
Can't use colon in site name

### ISSUE THREAD

**Issue by corgana** [constantoine/totp-rs#68]
Original bug report on LemmyNet: https://github.com/LemmyNet/lemmy/issues/4518

 Our Lemmy instance site name uses a colon, which apparently prevents 2FA from being enabled:

`CouldntGenerateTotp: Issuer can't contain a colon. "Star Trek: Website" contains a colon`

They told me it was really an issue with totp-rs, so I am letting you know!

**Comment by constantoine** [comment]
Hi! Because of the way the de-facto [standard](https://github.com/google/google-authenticator/wiki/Key-Uri-Format) works, the issuer parameter can't contain nor a `:` nor its url-encoded `%3A` form.

Right now, you might want to consider omitting the colon entitely. I feel like silently accepting invalid user input is probably not a great solution
